<?php

namespace EventsBundle\Repository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{
}
