<?php

namespace EventsBundle\Repository;

/**
 * InterestedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestedRepository extends \Doctrine\ORM\EntityRepository
{
}
