<?php

namespace EventsBundle\Repository;

/**
 * ParticiperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticiperRepository extends \Doctrine\ORM\EntityRepository
{
}
