<?php

namespace EventsBundle\Repository;

/**
 * ReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewsRepository extends \Doctrine\ORM\EntityRepository
{
}
