<?php

namespace MaintenanceBundle\Repository;

use MaintenanceBundle\Entity\mechanicien;

/**
 * mechanicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mechanicienRepository extends \Doctrine\ORM\EntityRepository
{


    public function getMechanicienbyPrix()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM MaintenanceBundle:Mechanicien m 
ORDER BY m.prix ASC");
        return $query->getResult();
    }
}
